### ISSUE TITLE
2d poses from 3d pose

### ISSUE THREAD

**Issue by alsehaimaa** [Nicholasli1995/EvoSkeleton#61] opened 2021-10-11 14:25 UTC
hi
how can I extract 2d poses from  the resulted 3d pose (2d pose front view, back view, and side view)
thanks

**Comment by Nicholasli1995** [comment] 2021-10-12 04:43
> hi how can I extract 2d poses from the resulted 3d pose (2d pose front view, back view, and side view) thanks

You can project the 3D pose to 2D with your camera parameters. Use different extrinsic rotation/translation for different views. Method in this repo that can be used is:
https://github.com/Nicholasli1995/EvoSkeleton/blob/b2b355f4c1fa842709f100d931189ce80008f6ef/libs/dataset/h36m/cameras.py#L8

**Comment by alsehaimaa** [comment] 2021-10-12 08:29
thanks for your replay, i am trying to do it for my own images where i do not have such information is there any default value for it.
Thanks in advance

**Comment by Nicholasli1995** [comment] 2021-10-13 07:16
> thanks for your replay, i am trying to do it for my own images where i do not have such information is there any default value for it. Thanks in advance

You do not need many parameters to simulate a pin-hole camera. Assume you have 3d pose [x, y, z] in the camera coordinate system (this repo contains it) and you can project it to the screen as [fx/z, fy/z] where f is your focal length. I would suggest you take a look at camera models. See https://docs.opencv.org/4.5.3/d9/d0c/group__calib3d.html for example.

**Comment by alsehaimaa** [comment] 2021-10-14 09:22
Thanks for your replay
I am trying to use it for my own images i generate the pose using h36mpose.py and then run the inference but can i ask how to generate the stats.npy file ?

**Comment by Nicholasli1995** [comment] 2021-10-15 02:51
> Thanks for your replay I am trying to use it for my own images i generate the pose using h36mpose.py and then run the inference but can i ask how to generate the stats.npy file ?

Use this inference script [https://github.com/Nicholasli1995/EvoSkeleton/blob/master/examples/inference.py](). Download the file following the instruction here [https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/TRAINING.md]().

**Comment by alsehaimaa** [comment] 2021-10-15 08:30
thanks so much for your replay I follow the instructions I just have trouble showing the 2d projection from 3d pose as follows
![index1](https://user-images.githubusercontent.com/49231780/137456890-bdb82004-f5ac-428e-8294-055c8627f9b7.png)

:
![index](https://user-images.githubusercontent.com/49231780/137456926-1efa8309-1f56-4ada-b680-7c813593a4e0.png)
![index5](https://user-images.githubusercontent.com/49231780/137456973-08c2b2fb-6d6e-4d43-8b90-b5644c6919f8.png)
![index4](https://user-images.githubusercontent.com/49231780/137456974-48715c6b-1aad-498f-893c-b714d81e9cd1.png)
![index3](https://user-images.githubusercontent.com/49231780/137456976-f9853826-46d7-4b59-b614-696849b8568b.png)

How can I visualize it right so I can see how accurate the projected 2d poses?

Thanks for everything, the code and support.

**Comment by alsehaimaa** [comment] 2021-10-15 13:00
i try to use the following code but yet did not get it

`def project_to_cameras(poses):
    """
    Project 3d poses using camera parameters
    input: 
        3D poses: [n_pose, pose length]
        cams: list of camera parameters
    return: list of 2D projections for each camera
    cams:
    """
    p_2d = []
    rcams= np.load('/Pose_for_Re-id/EvoSkeleton_master/cameras.npy', allow_pickle=True).item()
    #print('befor adding')
    cams = add_virtual_cams(rcams)
    #print('after adding')
    # By default, all actions are used
    ncams=4
    for cam in range(ncams):
        R, T, f, c, k, p, name = cams[(1, cam+1)]
        
        pts2d, _, _, _, _ = cameras.project_point_radial(np.reshape(poses, [-1, 3]), R, T, f, c, k, p )
        
        f = plt.figure(figsize=(9, 9))
        ax4 = plt.subplot(131)
        plt.title('2D key-point inputs: {:d}*2'.format(16))
        ax4.set_aspect('equal')
        ax4.invert_yaxis()
        skeleton_pred = None
           
        s2d=pts2d
        show2Dpose(np.reshape( pts2d, [-1, len(H36M_NAMES)*2]),ax4)
        p_2d.append(np.reshape( pts2d, [-1, len(H36M_NAMES)*2]))
        
    return p_2d`
the results was
![index15](https://user-images.githubusercontent.com/49231780/137490790-899e53be-5274-4844-b73a-dc96e06c11e8.png)
![index13](https://user-images.githubusercontent.com/49231780/137490795-e49640a7-6c91-4b7f-a293-4ae99cc58fd0.png)
![index12](https://user-images.githubusercontent.com/49231780/137490796-eead7d47-1c1a-4f60-89b0-03863e50d55f.png)
![index11](https://user-images.githubusercontent.com/49231780/137490797-309f8463-fec7-4573-b07b-595940d98b4a.png)
:

**Comment by alsehaimaa** [comment] 2021-10-15 15:17
If I need to rotate around the y-axis what should I change?

**Comment by Nicholasli1995** [comment] 2021-10-16 06:54
> If I need to rotate around the y-axis what should I change?

See ax.set_xlim/set_ylim to control your 2D plot. Change R and T to the camera pose that you need.

**Comment by alsehaimaa** [comment] 2021-10-18 08:03
Thanks but wen i change the anagle in add_virtual_cams to:
`new_R, new_T = get_new_camera(R.T, T, [0.,angle, 0.])` nothing changed.

**Comment by Nicholasli1995** [comment] 2021-10-18 14:12
> Thanks but wen i change the anagle in add_virtual_cams to: `new_R, new_T = get_new_camera(R.T, T, [0.,angle, 0.])` nothing changed.

You do not understand the code and coordinate transformation and I don't have time for beginner tutorial. Why not you upload your 3D pose and I simply write you a script to run? You can create a page in the discussion and I'm closing this issue since it's not a bug.

**Closed as completed by Nicholasli1995** 2021-10-18 14:12 UTC
